"""Add User model and many-to-many table

Revision ID: d77ab1b32d6c
Revises: 556bc644008b
Create Date: 2025-12-04 20:47:03.165091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77ab1b32d6c'
down_revision: Union[str, None] = '556bc644008b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
